name: Angular CI

on:
  push:
    branches:
      - jekasrs-patch-pipeline
      - test/*
      - dev
  pull_request:
    types: [closed]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: |
        cd code/
        npm install

    - name: Build Angular project
      run: |
        cd code/
        ng build

    - name: Run tests
      run: |
        cd code/
        ng test
